apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: test-db
spec:
  forProvider:
    region: eu-central-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "12.8"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: test
    name: test-db
